version: "3.7"

services:
  http:
    build:
      context: .
      target: nginx
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - app
    ports:
      - "8142:80"

  app:
    build:
      context: .
      target: app
    restart: always
    environment:
      - XHGUI_MONGO_HOSTNAME=mongo
      - XHGUI_MONGO_DATABASE=xhprof

  mongo:
    image: percona/percona-server-mongodb:3.6
    # (case sensitive) engine: mmapv1, rocksdb, wiredTiger, inMemory
    command: --storageEngine=wiredTiger
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=xhprof
    volumes:
      - ./mongo.init.d:/docker-entrypoint-initdb.d
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  webroot-share:
  mongodb:

# vim:ts=2:sw=2:et
